In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/customer.csv')

In [ ]:
data.sample(5)

    age  gender   review education purchased
38   45  Female     Good    School        No
27   69  Female     Poor        PG        No
23   96  Female     Good    School        No
47   38  Female     Good        PG       Yes
29   83  Female  Average        UG       Yes

In [ ]:
data = data.iloc[:,2:]

In [ ]:
data.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,0:2],data.iloc[:,-1],test_size=0.2)

In [ ]:
X_train

     review education
8   Average        UG
43     Poor        PG
45     Poor        PG
27     Poor        PG
18     Good    School
21  Average        PG
17     Poor        UG
42     Good        PG
29  Average        UG
31     Poor    School
39     Poor        PG
4   Average        UG
26     Poor        PG
35     Poor    School
37  Average        PG
2      Good        PG
32  Average        UG
14     Poor        PG
49     Good        UG
47     Good        PG
15     Poor        UG
0   Average    School
41     Good        PG
7      Poor    School
40     Good    School
11     Good        UG
44  Average        UG
25     Good    School
19     Poor        PG
22     Poor        PG
20  Average    School
24  Average        PG
9      Good        UG
28     Poor    School
13  Average    School
33     Good        PG
36     Good        UG
1      Poor        UG
10     Good        UG
5   Average    School

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train_enc = oe.transform(X_train)
X_test_enc = oe.transform(X_test)

In [ ]:
X_train_enc = pd.DataFrame(X_train_enc, columns= X_train.columns)
X_test_enc = pd.DataFrame(X_test_enc, columns= X_test.columns)
X_train_enc.head(5)
X_test_enc.head(5)

   review  education
0     0.0        0.0
1     1.0        0.0
2     2.0        0.0
3     2.0        0.0
4     0.0        1.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
y_train_enc = le.transform(y_train)
y_test_enc = le.transform(y_test)

In [ ]:
y_train_enc

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1])

In [ ]:
y_train_enc = pd.DataFrame(y_train_enc, columns=[y_train.name])
y_test_enc = pd.DataFrame(y_test_enc, columns=[y_test.name])
y_train_enc.head(5)
y_test_enc.head(5)

   purchased
0          0
1          0
2          0
3          0
4          1